# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae944b8de6462da2bd4a6850d91bac9ee91fe87314c5fdeec7e880926098f62b6d75b1697d3569f09bae48d6b849f12d85fc5e747cddbcdd596a2c3d984e8533

test:
  secret_key_base: ad12bd2a1885777f11f0ead09c46252ad49331332a288cd75d8ab13daf010b1eaab2b249986a26e563f4c607a42e7fd1129564918954c7b451794a4069f08199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
